### ISSUE TITLE
MultiDict.viewitems() is inconsistent with MultiDict.items()

### ISSUE THREAD

**Issue by JonathanRRogers** [pallets/werkzeug#942] opened 2016-05-28 20:36 UTC
I'm using Python 2.7 and werkzeug 0.11.3.

MultiDict.items() only returns the first value for each key by default. MultiDict.viewitems() always returns a list of the values for each key. It appears that there is no custom implementation of viewitems() so we're simply getting dict's implementation.

**Comment by untitaker** [comment] 2016-05-28 20:40
That is a bug and caused by MultiDict subclassing from `dict`.

**Comment by alexpantyukhin** [comment] 2016-07-26 16:41
The same thing for `viewkeys()` and `viewvalues()` methods. Actually these returns inner `dict_items`, `dict_keys` and `dict_values` types respectively.
What is just return iterators of special methods? For example:

```
    def viewitems(self):
        return self.items()
```

I think it would be enough. What do you think?

**Comment by untitaker** [comment] 2016-08-12 13:45
Fixed by https://github.com/pallets/werkzeug/pull/968

**Closed by untitaker** 2016-08-12 13:45 UTC
Labels: bug
