### ISSUE TITLE
`MultiDict` behavior for nested dicts changed in 3.1.0

### ISSUE THREAD

**Issue by berkanteber** [pallets/werkzeug#2996] opened 2024-11-07 09:12 UTC
`MultiDict` behavior for nested dicts changed in 3.1.0. It's probably because of this commit: 0294d88b9c10fe079ecfe9e02129d52b1e95de54.

For dicts:
- `isinstance(value, (tuple, list)` is `False`
- `isinstance(value, cabc.Collection) and not isinstance(value, str)` is `True`

So, for `d = {'foo': {'bar': {'baz'}}}`:

On `Werkzug==3.0.4`:
```pycon
>>> MultiDict(d)
MultiDict([('foo', {'bar': {'baz'}})])
>>> MultiDict(d).to_dict() == d
{'foo': {'bar': {'baz'}}}
```

On `Werkzeug==3.1.0` (and forward):
```pycon
>>> MultiDict(d)
MultiDict([('foo', 'bar')])
>>> MultiDict(d).to_dict() == d
{'foo': 'bar'}
```

On Python 3.11, but shouldn't be relevant.

**Comment by davidism** [comment] 2024-11-07 14:36
Duplicate of #2994

**Closed by davidism** 2024-11-07 14:36 UTC
