### ISSUE TITLE
Downgrade doesn't fix 'werkzeug.contrib' Error

### ISSUE THREAD

**Issue by irshad-io** [pallets/werkzeug#2167] opened 2021-06-20 19:55 UTC
The issue I am facing is that ```Werkzeug 1.0.0``` has removed deprecated code, including all of  ```Werkzeug.contrib``` so when I use flask-sessions I get

```
from werkzeug.contrib.cache import FileSystemCache
ModuleNotFoundError: No module named 'werkzeug.contrib'
```
So the solution suggested is to downgrade the ```werkzeug to 0.16.0``` which I did. But now the issue is
```
cannot import name 'ContextVar' from 'werkzeug.local'
```
For which the solution provided is to upgrade werkzeug to 2.0 or above.

What should I do to fix the flask-Sessions? How can I store session securely? 

I saw some alternatives to import ``` from cachelib import FileSystemCache ``` instead of ``` from werkzeug.contrib.cache import FileSystemCache``` in ```sessions.py``` but the issue is it doesn't encrypt the session files.

How can I fix this issue?

Also there is an issue with flask sessions that the sessions are not cleared when the browser is closed I have specifically given ```app.config["SESSION_PERMANENT"] = False``` at the beginning.

Environment:

- Python version: 3.9.5
- Flask version: 2.0.1
- Werkzeug version: 2.0.2

**Comment by ThiefMaster** [comment] 2021-06-20 19:56
Not a werkzeug issue; duplicate of pallets/flask#4166

**Closed by ThiefMaster** 2021-06-20 19:56 UTC
