### ISSUE TITLE
Backslash doesn't work with string URL Converter

### ISSUE THREAD

**Issue by deepaknc** [pallets/werkzeug#759] opened 2015-08-07 00:53 UTC
I have this route

```
@app.@app.route(/resource/<string:myresource>/details')
def handler(myresource):
  ....
  ...
```

When I have a leading backslash in the name, it doesn't seem to be getting routed correctly.

This works:
/resource/testresource/details/

This does not work:
/resource/%5Ctestresource/details

Is this expected? What am I doing wrong?

**Comment by edk0** [comment] 2018-07-17 12:00
Closing this because it's really old and I can't reproduce.

**Closed by edk0** 2018-07-17 12:00 UTC
