### ISSUE TITLE
secure-cookie is not released on pypi

### ISSUE THREAD

**Issue by azmeuk** [pallets/werkzeug#1672] opened 2019-11-28 10:22 UTC
The [bug report](https://github.com/pallets/secure-cookie/issues/1) on secure-cookie did not receive any attention. I open a discussion here because this repository seems a bit more popular. If you are annoyed by the double issue, do not hesitate to close this one.

Since 0.15, werkzeug displays this warning, advising to install secure-cookie. But several months later, secure-cookie still has not been released on pypi. So users get a warning they cannot fix. Is there some remaining tasks preventing to release secure-cookie on pypi? Is there something one can do to help?

```
DeprecationWarning: 'werkzeug.contrib.sessions' is deprecated as of version 0.15 and will be removed in version 1.0. It has moved to https://github.com/pallets/secure-cookie.
DeprecationWarning: 'werkzeug.contrib.securecookie' is deprecated as of version 0.15 and will be removed in version 1.0. It has moved to https://github.com/pallets/secure-cookie.
```

**Comment by robjampar** [comment] 2019-12-16 10:59
any updates on this, am interested in getting rid of this warning too

**Comment by davidism** [comment] 2020-01-03 15:10
duplicate of https://github.com/pallets/secure-cookie/issues/1

**Closed by davidism** 2020-01-03 15:10 UTC
