### ISSUE TITLE
SIGTERM aren't sent to reloader child process

### ISSUE THREAD

**Issue by sim6** [pallets/werkzeug#2634] opened 2023-04-02 00:29 UTC
Running in debug mode with reloader the SIGTERM isn't sent to reloader child process instead the parent process exits, so child process cannot shutdown gracefully.

See also https://github.com/pallets/werkzeug/pull/2633

Environment:

- Python version: 
- Werkzeug version:

**Comment by davidism** [comment] 2023-04-03 13:29
Duplicate of https://github.com/pallets/werkzeug/issues/58, quoting from there:

> Until we can get a reproducible scenario, I will close this as it cannot be reproduced in the latest version of Docker and Werkzeug.

**Closed by davidism** 2023-04-03 13:29 UTC
