### ISSUE TITLE
performance issue for some data handling in MultipartDecoder

### ISSUE THREAD

**Issue by zhangchunlin** [pallets/werkzeug#2512] opened 2022-09-14 06:51 UTC
The performance issue for data handling in MultipartDecoder( issue #2430 ) still exist.

- Generate a file with code:
```
def test52():
    with open("uploadfile.dat","wb") as f:
        def _gen():
            yield b"\r"
            for i in range(10000000):
                yield b"1234567890"
        for i in _gen():
            f.write(i)
if __name__ == '__main__':
    test52()
```

- Extract this project: [upload_test.zip](https://github.com/pallets/werkzeug/files/9563566/upload_test.zip)
- pip install -r requirements.txt in this project
- pip install werkzeug version you want to test
- run command "uliweb develop" in this project
- access http://localhost:8000
- upload the file generate above

upload can be finished with several seconds, but it need about 47 seconds with werkzeug 2.0.2 and 2.2.2, if the file is bigger the upload time will increase with o(n^2) growth.

Environment:

- Python version:3.9.7
- Werkzeug version: 2.2.2 and 2.0.2

**Comment by zhangchunlin** [comment] 2022-09-14 08:03
Simpler to reproduce the problem may be these:

Add this function to tests/test_formparser.py:
```
    def test_multipart_slow(self):
        def parse_multipart(stream, boundary, content_length):
            parser = formparser.MultiPartParser(content_length)
            return parser.parse(stream, boundary, content_length)
        def _gen():
            yield b"\r"
            for i in range(1000000):
                yield b"1234567890"
        data = b"".join(_gen())
        pytest.raises(ValueError, parse_multipart, io.BytesIO(data), b"foo", len(data))
```
Then run:
`pytest test_formparser.py -k test_multipart_slow`

**Comment by zhangchunlin** [comment] 2022-09-14 09:45
@pgjones I explain in [this comment](https://github.com/pallets/werkzeug/issues/2430#issuecomment-1168189302), but the logic is for werkzeug 2.0.2, I am not sure for 2.2.2, but from the test result, the handling time of 2.0.2 and 2.2.2 is almost the same, so I think it is still o(n^2) in 2.2.2, if we increase the file size, the time will be much longer, so the test result also prove that.

**Comment by pgjones** [comment] 2022-09-14 14:26
I can't reproduce this, the test you've provided seems to scale linearly for me.

**Comment by zhangchunlin** [comment] 2022-09-15 10:47
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">


</head>
<body>

time unit: seconds

  | 2.0.2 | 2.2.2 | main(b1911cd)
-- | -- | -- | --
50m | 11 | 11 | 11
100m | 43 | 43 | 36
150m | 82 | 75 | 97
200m | 171 | 132 | 153
250m | 270 | 207 | 227
300m | 307 | 328 | 299



</body>

</html>

**Comment by davidism** [comment] 2022-09-15 15:08
Given that a maintainer cannot reproduce this, I'm closing this. It seems like something that is local to your machine, or you haven't provided enough detail to reproduce the issue.

**Closed by davidism** 2022-09-15 15:08 UTC

**Comment by zhangchunlin** [comment] 2022-09-16 01:47
It not only my local, in other's computer, and our servers, all can reproduce this problem, actually some users report that when they upload files.

**Comment by davidism** [comment] 2022-09-16 02:04
Ok, but you haven't managed to convey that in a way that we can address, so it's on you at this point to diagnose it further.

**Comment by zhangchunlin** [comment] 2022-09-16 02:33
I think I have given the steps how to reproduce in the first description, maybe you guys haven't try it.
I will try to make a PR later with another way, make the user can increase the buffer_size by give a parameter, which I think it is a good choice to users.

**Comment by davidism** [comment] 2022-09-16 02:55
We have, in fact, tried it, as we stated earlier.

**Comment by zhangchunlin** [comment] 2022-09-16 05:41
I have submit the PR #2514, you can have a look, 

<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

</head>
<body>

Data between different buff_size:

  | 128 * 1024 | 512 * 1024 | 1024 * 1024
-- | -- | -- | --
50m | 4 | 1 | 1
100m | 20 | 6 | 3
150m | 43 | 14 | 8
200m | 70 | 20 | 12
250m | 119 | 33 | 16
300m | 252 | 52 | 22



</body>

</html>

**Comment by pgjones** [comment] 2022-09-16 08:44
Whilst increasing the buffer size, does reduce the number of `next_event` calls, and hence regex searches. I can't see the same improvement you have in your tables, nor do I see any indication of quadratic scaling.

**Comment by zhangchunlin** [comment] 2022-09-17 01:46
You mean you don't understand why the buffer_size will can cause so much improvement? I am not sure I understand your question.
And for "any indication of quadratic scaling", from the data I am not so sure, but it is obviours that the increasing is not linear.

**Comment by zhangchunlin** [comment] 2022-09-17 08:20
I add some log and get some more detail data, now my understanding about this problem is, for this kind of data, at last werkzeug will read all the data into memory, for example 100MBytes data, if buffer size is 1024*1024, it will split the data into about 96 data blocks to extend, and if buffer size is 64*1024, it will split the data into 1526 data blocks to extend, so the non-linear increasing is the buffer extend times.

2022-09-17 16:10:08 INFO #95 buffer +1048576 data, 98565991
2022-09-17 16:10:08 INFO #96 buffer +385482 data, 99614567
buffer_size: 1048576, time: 3.7 seconds, speed: 26996949.4 bytes/s

2022-09-17 16:11:50 INFO #190 buffer +524288 data, 99090279
2022-09-17 16:11:50 INFO #191 buffer +385482 data, 99614567
buffer_size: 524288, time: 6.0 seconds, speed: 16612928.1 bytes/s

2022-09-17 16:12:35 INFO #762 buffer +131072 data, 99745639
2022-09-17 16:12:35 INFO #763 buffer +123338 data, 99876711
buffer_size: 131072, time: 19.9 seconds, speed: 5020752.2 bytes/s

2022-09-17 16:13:33 INFO #1525 buffer +65536 data, 99876711
2022-09-17 16:13:33 INFO #1526 buffer +57802 data, 99942247
buffer_size: 65536, time: 38.4 seconds, speed: 2607136.3 bytes/s

**Comment by pgjones** [comment] 2022-09-17 09:21
The underlying call is `bytearray` `extend`, which I think is [this](https://github.com/python/cpython/blob/main/Objects/bytearrayobject.c#L1692) code. Looks like the resize strategy is to create the exact required size on each extend, so clearly quicker if this is called less.

**Comment by zhangchunlin** [comment] 2022-09-18 00:35
```
>>> 3.7/96
0.03854166666666667
>>> 6/191
0.031413612565445025
>>> 19.9/763
0.026081258191349932
>>> 38.4/1526
0.02516382699868938
```
Look like the times of function invoked is the main factor, buffer size is not the main factor.

So what do you think about the adding of buffer_size parameter? That won't change any default behavior of werkzeug, but give user choices to optimize the performance.

**Comment by davidism** [comment] 2022-09-18 02:09
I do not want a configuration for this. Identify and fix the actual issue with the implementation.

**Comment by zhangchunlin** [comment] 2022-09-18 02:38
Do you mean choose some way for example reimplementing a new bytearray.extend which don't having this performance issue?

**Comment by davidism** [comment] 2022-09-18 02:42
I don't know, if I did then we would have already fixed it. If you think there's a performance issue with bytearray, then you need to report that to Python, not us.

**Comment by zhangchunlin** [comment] 2022-09-18 02:57
My thinking is different, I think that is mainly because the buffer size too small, I don't have so much high expectation to a Python lib, Python is not C/rust, and the cost of a function call in Python is more expensive than C/rust, I don't think it is a right way to optimaze for Python.

**Comment by davidism** [comment] 2022-09-18 02:59
Ok, I think we're at an impasse then and you'll need to move on from this.

**Comment by zhangchunlin** [comment] 2022-09-18 03:14
OK, if you insist to hardcode the buffer size, I will think about make another package release just add the parameter exposed.
