### ISSUE TITLE
Duplicate "Date" header in send_file

### ISSUE THREAD

**Issue by delta6862** [pallets/werkzeug#2711] opened 2023-05-31 13:17 UTC
Hey,

It looks like the send_file function within werkzeug (which by is used in Flask to serve static files) will send a duplicate "Date" header.

For example, when running the following code (Flasks send file is a wrapper for the identical werkzeug function):
```python
from flask import Flask, send_file

app = Flask(__name__)

@app.route('/')
def download_file():
    filename = 'example.txt'
    return send_file(filename, as_attachment=True, max_age=2, last_modified=1)

if __name__ == '__main__':
    app.run(port=1337)
```

You can spot the identical headers using curl
```
curl -v http://localhost:1337/  
*   Trying 127.0.0.1:1337...
* Connected to localhost (127.0.0.1) port 1337 (#0)
> GET / HTTP/1.1
> Host: localhost:1337
> User-Agent: curl/8.0.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: Werkzeug/2.1.2 Python/3.10.10
< Date: Wed, 31 May 2023 10:25:17 GMT
< Content-Disposition: attachment; filename=example.txt
< Content-Type: text/plain; charset=utf-8
< Content-Length: 3
< Last-Modified: Thu, 01 Jan 1970 00:00:01 GMT
< Cache-Control: public, max-age=2
< Expires: Wed, 31 May 2023 10:25:19 GMT
< ETag: "1685528193.4676535-3-3467185288"
< Date: Wed, 31 May 2023 10:25:17 GMT
< Connection: close
```

While not a breaking bug, there shouldn't be a reason to have duplicate, identical headers.

Environment:
- Python version: 3.10
- Werkzeug version :2.3.0

**Comment by davidism** [comment] 2023-05-31 13:50
Duplicate of https://github.com/pallets/werkzeug/issues/2500

**Closed by davidism** 2023-05-31 13:50 UTC
