### ISSUE TITLE
ProxyFix 0.15 default behavior no longer to HTTP->HTTPS conversion from proxy forwarder

### ISSUE THREAD

**Issue by corby** [pallets/werkzeug#1543] opened 2019-05-14 18:47 UTC
The ProxyFix object in 0.14 by default would pay attention to the X-Forwarded-Proto: https headers used by AWS ELB servers.
The following line was all I had to add to my flask app:
wsgi_app = ProxyFix(wsgi_app)

In 0.15 this behavior was modified and all my flask apps broke if they were behind an SSL enabled load balancer.

This is clearly a bug as it breaks backward compatibility with a minor release.

**Comment by ThiefMaster** [comment] 2019-05-14 18:48
Pass `x_proto=1`. But yeah, the defaults should probably be changed...

**Comment by davidism** [comment] 2019-05-14 19:10
Duplicate of #1484

**Closed by davidism** 2019-05-14 19:10 UTC
