### ISSUE TITLE
werkzeug ver. 2.1.0 is not compatible with dash lib 2.3.0

### ISSUE THREAD

**Issue by vetonyx** [pallets/werkzeug#2362] opened 2022-03-30 07:05 UTC
import error on start dash app.
ImportError: cannot import name 'get_current_traceback' from 'werkzeug.debug.tbtools'

- Python version: 3.8.10
- Werkzeug version: 2.1.0

**Comment by davidism** [comment] 2022-03-30 12:51
Duplicate of https://github.com/plotly/dash/issues/1992

**Closed by davidism** 2022-03-30 12:51 UTC
