### ISSUE TITLE
[0.15.1] itsdangerous rasies BadSignature when loading token using TimedJSONWebSignatureSerializer

### ISSUE THREAD

**Issue by iROCKBUNNY** [pallets/werkzeug#1489] opened 2019-03-23 14:00 UTC
No such issue with Werkzeug==0.14.1

in: 

```
data = serial.loads(token)
```

rasies:

```
itsdangerous.exc.BadSignature: Signature b"*********" does not match
```

**Comment by davidism** [comment] 2019-03-23 17:15
Werkzeug does not affect itsdangerous. Duplicate of https://github.com/pallets/itsdangerous/issues/120

**Closed by davidism** 2019-03-23 17:15 UTC

**Comment by iROCKBUNNY** [comment] 2019-03-23 20:03
Sorry, it turned out to be a decoder issue on my side. Just added `.decode('ascii')` to `serial.dump(json_data)` and saved my day!
