### ISSUE TITLE
url parameters casting bytes to str

### ISSUE THREAD

**Issue by fuhrysteve** [pallets/werkzeug#1502] opened 2019-04-02 21:05 UTC
Hi there! I noticed a change in behavior in werkzeug 0.15.x whereby url parameters used to be safe to send as bytes (on python 3.6).

I apologize for not showing a more direct example in werkzeug, but like most users of werkzeug - I don't use it directly - I use it through flask.

Demonstration (using Flask)

```python
from flask import Flask, url_for

app = Flask(__name__)
app.config['SERVER_NAME'] = 'www.foo.com'


@app.route('/<string:foo>')
def hello(foo):
    return 'Hello, World!'


with app.app_context():
    print(url_for('hello', foo=b'bar'))
```

With `werkzeug<0.15`, this will output:

```
http://www.foo.com/bar
```

However as of `werkzeug>=0.15`, it now returns this malformed url:

```
http://www.foo.com/b%27bar%27
```

I would expect that if `werkzeug` isn't going to decode bytes for you anymore, that it ought to raise a `TypeError` indicating that `bytes` is no longer safe to pass in.

I hope this example makes sense! Thanks for reviewing my issue - I'd be happy to (attempt to) submit a pull request if y'all agree that this is not desirable behavior.

**Comment by edk0** [comment] 2019-04-03 12:35
I'll have a look at this. We (evidently) don't have tests for this, so I suspect accepting bytes was never intended behaviour.

**Comment by edk0** [comment] 2019-04-03 14:04
Seems like fixing this is as easy as catching it: https://github.com/edk0/werkzeug/commit/794eb16b23096db9e51c7cd58a7ded9086f8c930 so I'm inclined that way.

**Comment by davidism** [comment] 2019-04-03 14:08
@edk0 I don't think you changed that code in your PR, was there a related change that cause this?

I'm not opposed to this, but it seems a little weird to be passing bytes directly in a URL. @fuhrysteve Under what circumstances do you have UTF-8 bytes and not the text? If you're really passing bytes, and not text, I'd expect to pass them as Base64, which would require a custom converter.

**Comment by fuhrysteve** [comment] 2019-04-03 14:28
@davidism in my case it was a json web token. PyJWT returns bytes by default.

```python
In [1]: import jwt                                                                                                                                                                                           

In [2]: jwt.encode({'some': 'payload'}, 'secret', algorithm='HS256')                                                                                                                                         
Out[2]: b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzb21lIjoicGF5bG9hZCJ9.Joh1R2dYzkRvDkqv3sygm5YyK8Gi4ShZqbhK2gxcs2U'
```

**Comment by edk0** [comment] 2019-04-03 14:53
@davidism I believe it was an unintended consequence—I swapped out the implementation of `to_url` for a faster one that pre-baked but needed bytes as input; the usual behaviour is to convert to `text_type` and then encode, so I did that, and didn't notice the change in behaviour for `bytes`.

I do wonder if it might be a better idea to add a bytes converter and have `BaseConverter` throw an error.

**Comment by fuhrysteve** [comment] 2019-04-03 21:42
@edk0 isn't everything passing through `UnicodeConverter` here, which is the "default converter"? At a glance, I'd suspect it ought to go there and have `BaseConverter` or something beneath it `raise TypeError` prior to any conversion to a string.

I share your hesitation to make `utf-8` assumptions in `BaseConverter`

**Comment by edk0** [comment] 2019-04-04 09:30
It's not actually making UTF-8 assumptions, just URL encoding the bytes as-is, but it does seem wrong.

I'm torn because we did special-case bytes in the past. Maybe we should add a converter that passes bytes as-is, and have `BaseConverter` do the same for now, but with a warning.

**Comment by greyli** [comment] 2019-04-22 03:25
Same problem here. I use itsdangerous to generate JWT token for user confirmation in this way:

```py
from flask import current_app
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer

def generate_token(user, operation, expire_in=None, **kwargs):
    s = Serializer(current_app.config['SECRET_KEY'], expire_in)

    data = {'id': user.id, 'operation': operation}
    data.update(**kwargs)
    return s.dumps(data)
```
The return value will be in bytes type, like `b'eyJhbGciOiJ...YmQ'`. Then I generate the confirmation URL with the token returned in email template:
```
{{ url_for('auth.confirm', token=token, _external=True) }}
```
With Werkzeug >= 0.15, It end up to something like this (Notice the unnecessary `b%27` and `%27` part in the URL):
```
http://127.0.0.1:5000/confirm/b%27eyJhbGciOiJ...YmQ%27
```
Here is the view function that handle token confirmation:
```py
@auth_bp.route('/confirm/<token>')
@login_required
def confirm(token):
    print(token)  # b%27eyJhbGciOiJ...YmQ%27
```
The correct token value should be just `eyJhbGciOiJ...YmQ`, so the token confirmation will be failed finally.

**Closed** 2019-05-08 18:46 UTC
