### ISSUE TITLE
Local variables not available in debug console in version 1.0

### ISSUE THREAD

**Issue by cgarrard** [pallets/werkzeug#1746] opened 2020-03-11 00:14 UTC
Take this simple script:

```python
from werkzeug.wrappers import Request, Response

some_global_variable = True

@Request.application
def application(request):
    msg = 'Hello, World!'
    return Response(msg2)

if __name__ == '__main__':
    from werkzeug.serving import run_simple
    run_simple('localhost', 4000, application,
               use_reloader=True, use_debugger=True, use_evalex=True)
```

As expected, the application crashes when it tries to create the response because `msg2` doesn't exist. With version 0.16.1 and Python 3.8, I can view the value of the `msg` variable in the debug console. But if I upgrade to version 1.0, `msg` is no longer defined. Global variables are available, however. Here's a screenshot:

![image](https://user-images.githubusercontent.com/4453816/76369784-57a50500-62fa-11ea-97cf-98a0a65a44a4.png)

**Comment by davidism** [comment] 2020-03-11 01:35
Duplicate of #1741

**Closed** 2020-03-13 17:21 UTC
