### ISSUE TITLE
MapAdapter.get_default_redirect calls url_quote twice

### ISSUE THREAD

**Issue by ghost** [pallets/werkzeug#152] opened 2012-01-07 10:35 UTC
``` python
def get_default_redirect(self, rule, method, values, query_args):
    ...
    ...
    domain_part, path = r.build(values)
    return self.make_redirect_url(
        path, query_args, domain_part=domain_part)
```

Both `r.build(...)` and `self.make_redirect_url(...)` call _url_quote_ internally, so this method returns broken URLs when they contain symbols (@$*~ etc.) or non-ascii charactors.

I think it should be:

``` python
    domain_part, path = r.build(values)
    path = url_unquote(path, self.map.charset)
    return self.make_redirect_url(
        path, query_args, domain_part=domain_part)
```

**Comment by davidism** [comment] 2019-09-25 16:43
Appears to be a duplicate of #432, fixed back in 0.9.

**Closed by davidism** 2019-09-25 16:43 UTC
Labels: routing
