### ISSUE TITLE
Add a network pytest mark for tests that use the network

### ISSUE THREAD

**Issue by mcepl** [pallets/werkzeug#2393] opened 2022-04-19 21:17 UTC
Sometimes it's useful to have the tests that use the network marked so they can be skipped easily when we know the network is not available.

This is useful for example on SUSE and openSUSE's build servers. When building our packages the network is disabled so we can assure reproducible builds (among other benefits). With this mark, it's easier to skip tests that can not succeed.

Patch suggesting the solution:
```diff
---
 pytest.ini            |    3 +++
 tests/test_serving.py |    5 +++++
 2 files changed, 8 insertions(+)

--- /dev/null
+++ b/pytest.ini
@@ -0,0 +1,3 @@
+[pytest]
+markers =
+    network: tests requiring network connection
--- a/tests/test_serving.py
+++ b/tests/test_serving.py
@@ -118,6 +118,7 @@ def test_windows_get_args_for_reloading(
     assert rv == argv


+@pytest.mark.network
 @pytest.mark.parametrize("find", [_find_stat_paths, _find_watchdog_paths])
 def test_exclude_patterns(find):
     # Imported paths under sys.prefix will be included by default.
@@ -157,6 +158,7 @@ def test_port_is_int():
         run_simple("127.0.0.1", "5000", None)


+@pytest.mark.network
 @pytest.mark.filterwarnings("ignore::pytest.PytestUnraisableExceptionWarning")
 @pytest.mark.parametrize("send_length", [False, True])
 def test_chunked_request(monkeypatch, dev_server, send_length):
@@ -241,6 +243,7 @@ def test_multiline_header_folding(standa
     assert data["HTTP_XYZ"] == "first\tsecond\tthird"


+@pytest.mark.network
 @pytest.mark.parametrize("endpoint", ["", "crash"])
 def test_streaming_close_response(dev_server, endpoint):
     """When using HTTP/1.0, chunked encoding is not supported. Fall
@@ -252,6 +255,7 @@ def test_streaming_close_response(dev_se
     assert r.data == "".join(str(x) + "\n" for x in range(5)).encode()


+@pytest.mark.network
 def test_streaming_chunked_response(dev_server):
     """When using HTTP/1.1, use Transfer-Encoding: chunked for streamed
     responses, since it can distinguish the end of the response without
@@ -264,6 +268,7 @@ def test_streaming_chunked_response(dev_
     assert r.data == "".join(str(x) + "\n" for x in range(5)).encode()


+@pytest.mark.network
 @pytest.mark.filterwarnings("ignore::pytest.PytestUnraisableExceptionWarning")
 def test_streaming_chunked_truncation(dev_server):
     """When using HTTP/1.1, chunked encoding allows the client to detect
```

[Complete build logs](https://github.com/pallets/werkzeug/files/8516491/_log.txt) with all packages used and steps taken to reproduce.

**Comment by davidism** [comment] 2022-04-25 13:47
The "network" tests don't access an external network that could affect reproducibility, they only connect to localhost to test the dev server.

**Comment by davidism** [comment] 2022-04-25 15:04
How can I disable networking to confirm that all necessary tests are marked? It would be helpful if you could make a PR.

**Comment by mcepl** [comment] 2022-04-25 15:42
I am sorry, I am a co-maintainer of over 2000 Python-related packages in openSUSE. I just cannot maintain checkouts of all those packages.

**Comment by davidism** [comment] 2022-04-25 15:46
Sorry, I don't have that expertise. Since these tests don't require external connections, and haven't been demonstrated to affect reproducibility, and I can't test that the mark will be accurate, I'm going to close this at this time. Happy to review a PR if you or someone else on your team can make one.

**Comment by davidism** [comment] 2022-04-25 15:51
I don't see how I would tell Docker to not allow localhost, and I don't have anything set up to run the tests in Docker. Since these tests don't require external connections, it would help if you could demonstrate how they affect reproducibility.

**Comment by davidism** [comment] 2022-04-25 15:51
I'm about to release 2.1.2, so if you want these marks in those tests, I'm going to need a resolution in the next few hours.

**Comment by davidism** [comment] 2022-04-25 16:38
It could also be that you're using a non-standard build process, that seems to be the issue with a lot of issues that OS packagers report. We expect to build with `python setup.py sdist` or preferably `python -m build`, and to be installed with `pip install`. `setup.py install` is not supported and may cause issues.

**Comment by davidism** [comment] 2022-04-26 13:50
Any update on this? It sound like this should be a bug reported to SUSE about their Python build process or network isolation.

**Comment by davidism** [comment] 2022-04-28 14:11
I'll add this mark because it's convenient to skip the tests that use the `dev_server` fixture since they're slow.

However, I would strongly encourage you to investigate why the tests are failing in your environment and address that there. While no one using Werkzeug from an operating system package should be using the development server, it still doesn't seem good to skip these tests in that context.

**Comment by mcepl** [comment] 2022-04-28 14:19
Sorry, I will get to this eventually, but I am currently swamped with other stuff (from our paying customers).

**Comment by davidism** [comment] 2022-04-28 14:24
What's the point of pointing out "paying customers". I mean, it draws attention to the fact that SUSE _isn't_ paying us, but is asking us to debug their build system, so now I'm sort of inclined to just close this?

**Comment by davidism** [comment] 2022-04-28 14:31
Speaking of paying customers, I noticed that SUSE is listed on Wikipedia as having $450 million in revenue, but as far as I'm aware has never donated to Pallets. Presumably, some fraction of your paying customers are deploying Flask, Jinja, or Click applications, so it would be really appreciated if SUSE made a donation to the Pallets organization.

**Comment by mcepl** [comment] 2022-04-28 14:54
1. I am just a poor engineer, nobody deciding anything about the money.
2. We usually don’t give up money. Our contribution to the upstream open source world is in a zillion manhours spent on creating patches, supporting our users, etc.

**Comment by davidism** [comment] 2022-04-28 14:59
I don't think I've seen a patch in a Pallets project from a SUSE employee, and you said you don't have time to make patches anyway.

**Closed** 2022-04-28 15:53 UTC

**Comment by mhils** [comment] 2022-04-28 20:10
> How can I disable networking to confirm that all necessary tests are marked? It would be helpful if you could make a PR.

FWIW I coincidentally looked into this just a few days ago for one of my FOSS projects. There's a reasonably simple way to disable internet connectivity when running tests via tox: https://github.com/mitmproxy/mitmproxy/blob/9d1821e920d6225578a0b65881d203a537186298/.github/workflows/main.yml#L88-L96

(I don't want to add any heat to the discussion, so I'll leave it at that. Thanks @davidism!)

**Comment by mcepl** [comment] 2022-04-28 21:08
OK, `dev_server` works for me, I have just discovered that I have mistakenly included in my patch also `tests/test_serving.py::test_exclude_patterns[_find_stat_paths]`, which has different problems. Let me file another ticket.
