### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by tommyjcarpenter** [pallets/werkzeug#1372] opened 2018-10-08 14:14 UTC
This morning when using a package that uses this package, I received the following warning messages. 

```
foo/python3.7/site-packages/werkzeug/datastructures.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Container, Iterable, MutableSet
foo/python3.7/site-packages/werkzeug/datastructures.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Container, Iterable, MutableSet
foo/python3.7/site-packages/werkzeug/datastructures.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Container, Iterable, MutableSet
```

**Comment by ThiefMaster** [comment] 2018-10-08 14:15
Duplicate of #1366 and #1351

Ignore it for now; we'll release an update before Python 3.8 is releasaed.

**Closed by ThiefMaster** 2018-10-08 14:15 UTC

**Comment by ssbarnea** [comment] 2018-12-31 18:19
This bug should be reopened because the fix was never shipped. The latest release is more than an year old  https://pypi.org/project/Werkzeug/#history and nobody sane can expect to add dependencies on unreleased versions.

This is more problematic because it would break the CI on any project that treats warnings as errors (like `py.test -Werror`).
