### ISSUE TITLE
2.2.0 breaks with ImportError: cannot import name 'parse_rule' from 'werkzeug.routing'

### ISSUE THREAD

**Issue by johnbazan** [pallets/werkzeug#2466] opened 2022-07-25 15:05 UTC
It just stopped working when used through Flask.
I had to force the version to 2.0.2 to keep it working.

The traceback I get is the following:

```
(venv) root@f8db108b508b:/usr/src/app# python manage.py
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from app import blueprint
  File "/usr/src/app/app/__init__.py", line 2, in <module>
    from flask_restx import Api
  File "/usr/local/lib/python3.8/site-packages/flask_restx/__init__.py", line 5, in <module>
    from .api import Api  # noqa
  File "/usr/local/lib/python3.8/site-packages/flask_restx/api.py", line 50, in <module>
    from .swagger import Swagger
  File "/usr/local/lib/python3.8/site-packages/flask_restx/swagger.py", line 18, in <module>
    from werkzeug.routing import parse_rule
ImportError: cannot import name 'parse_rule' from 'werkzeug.routing' (/usr/local/lib/python3.8/site-packages/werkzeug/routing/__init__.py)
```

Couldn't really take the time to debug and see if it's related to the other created issue.

**Comment by davidism** [comment] 2022-07-25 15:08
Duplicate of https://github.com/python-restx/flask-restx/issues/460

The line `/usr/local/lib/python3.8/site-packages/flask_restx/swagger.py` in the traceback indicates that this is an issue with Flask-RestX, and it's already been reported there.

It appears that Flask-RestX is only lightly maintained at best now. You may be better off using an actively maintained API extension like Flask-Resty, Flask-Smorest, APIFlask, Flask-Rebar, etc. if you want to continue to receive updates to Flask and Werkzeug.

**Closed by davidism** 2022-07-25 15:08 UTC

**Comment by johnbazan** [comment] 2022-07-25 15:11
Sounds fair enough.

Just last question: is `parse_rule` now deprecated?
Couldn't find anything related to this in the 2.2.0 changelog.

**Comment by davidism** [comment] 2022-07-25 15:11
It was never a public API.

**Comment by bbnil** [comment] 2022-07-25 16:26
duplicate of https://github.com/pallets/werkzeug/issues/2464
