### ISSUE TITLE
I got a problem when using python3.8 to run flask

### ISSUE THREAD

**Issue by somewheve** [pallets/werkzeug#1669] opened 2019-11-23 06:48 UTC
I try to use the virtual environment based on python 3.8 to running 
a flask program in Arch Linux.

But I got an error
```
TypeError: required field "type_ignores" missing from Module'
```
So I search it by google and find a way to solve it.

[link](https://bugs.python.org/issue35894)

and I change the code to the next version and it works 

> werkzeug/routing.py  line:950-952 

```
module = ast.fix_missing_locations(ast.Module([func_ast],[]))
code = compile(module, "<werkzeug routing>", "exec")
return self._get_func_code(code, func_ast.name)
```

Hope for your reply and fix

**Comment by aenglander** [comment] 2019-12-16 00:04
Can you add a code sample to reproduce as well as a `Pipenv.lock` file or the results of a `pip freeze` for me to reproduce the issue? I have been running Flask/Werkzeug in Python 3.8 for a bit  and don't have the same issue.

**Comment by davidism** [comment] 2019-12-16 01:10
This should have been fixed a while ago, are you using the latest version?

**Comment by davidism** [comment] 2019-12-16 21:52
Duplicate of #1551

**Closed by davidism** 2019-12-16 21:52 UTC

**Comment by ankitmaisuriya1997** [comment] 2020-03-28 12:40
"C:\Python 38\python.exe" "C:/Users/ANKIT/PycharmProjects/Flask App/main.py"
Traceback (most recent call last):
  File "C:/Users/ANKIT/PycharmProjects/Flask App/main.py", line 3, in <module>
    from werkzeug import secure_filename
ImportError: cannot import name 'secure_filename' from 'werkzeug' (C:\Python 38\lib\site-packages\werkzeug\__init__.py)

Process finished with exit code 1



Sir, please solve this error.
