### ISSUE TITLE
app.route mixes up parameters passed when multiple regex patterns are used

### ISSUE THREAD

**Issue by rosepark4861** [pallets/werkzeug#2590] opened 2023-02-17 00:57 UTC
We recently upgraded from Flask v1.1.2 to Flask v2.2.2 and were surprised when many of our project unit tests started failing because Flask v2.2.2 is not passing the correct parameters to a route function.  This worked correctly in the previous v1.1.2 which we were using but no longer works properly in v2.2.2.

The following python code example of a route which passes 3 parameters with regex expressions will replicate the bug:

```python
ALLOWED_METHODS = ["GET", "HEAD"]
DATE_PATTERN = "((\d{8}T\d{6}([.,]\d{1,3})?)|(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}([.,]\d{1,3})?))Z"
# Note that 2 date formats are supported using this date pattern
# if you want to see what this regex does, paste it into https://regexper.com/

@app.route('/<regex("\d+"):source_id>/'
        + '<regex("' + DATE_PATTERN + '"):start_time>/'
        + '<regex("' + DATE_PATTERN + '"):end_time>', methods=ALLOWED_METHODS)
def clipslist_id(source_id, start_time, end_time):
    print("clipslist_id parameters source_id {} start_time {} and end time {}".format(source_id, start_time, end_time))
    print("Valid parameters {}".format(end_time > start_time))
    return
```

Call the app.get function and pass in a uri such one of the following (two date formats are supported):

```
/22/2023-02-16T23:36:36.266Z/2023-02-16T23:46:36.266Z
/22/20230217T002724.998Z/20230217T003724.998Z
```

Note that in both of the example uri's above the 3rd datetime parameter value is 10 minutes after the 2nd datetime parameter value
When the uri gets routed to clipslist_id the function receives 3 parameters, but the 3rd parameter is not correct.  Instead of passing through the correct 3rd parameter the route code passes the 2nd parameter twice, once as the 2nd parameter, and again as the 3rd parameter.

The three parameters received by the function should have had the values for: source_id, start_time, and end_time
Instead the three parameters that the function received were: source_id, start_time, start_time
The end_time value was not passed to the function

Environment:
Python 3.8.10 (default, Nov 14 2022, 12:59:47)
Flask 2.2.2

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
5.15.0-58-generic

**Comment by davidism** [comment] 2023-02-17 01:03
Probably solved by https://github.com/pallets/werkzeug/issues/2582 which will be in 2.3 when it's released. It's also a duplicate of #2491, #2518, #2519, and possibly some others.

Quoting from my comment on #2491:

> Note that the `regex` converter is not provided by Werkzeug. You should report an issue to the library providing that converter.

**Comment by rosepark4861** [comment] 2023-02-21 19:11
I looked at the code change you referred to in #2582 and I see that it checks for a / character in the regex expression and then changes a `part_isolating` flag to false.

In the example I gave above none of the regex expressions contain a / character.  I am not sure exactly what the `part_isolating` flag alters the processing and it was not obvious to me whether is should be set to False or True when all the regex expression do *not* contain slashes.

I tried to test this in our code by attempting to explicitly modify the `part_isolating` flag in the `__init__` function.  I experimented by setting it to both False and True, but the app.route code continued to pass the wrong parameter values into the route handing function for every variation that I tried.

This is the code where I attempted to change the `part_isolating` flag to work around this issue. 

```
 class RegexConverter(BaseConverter):
    """
    This class is used to covert a Regex pattern to a Flask Regex pattern
    """
    def __init__(self, url_map, *items):
        super(RegexConverter, self).__init__(url_map)
        RegexConverter.part_isolating = False
        self.part_isolating = False
        self.regex = items[0]
```

I also tried the opposite

```
class RegexConverter(BaseConverter):
    """
    This class is used to covert a Regex pattern to a Flask Regex pattern
    """
    def __init__(self, url_map, *items):
        super(RegexConverter, self).__init__(url_map)
        RegexConverter.part_isolating = True
        self.part_isolating = True
        self.regex = items[0]
```

Is there a different way that I should have attempted to change the `part_isolating` flag to work around this issue?  Or is this issue not resolved by changing the value of the `part_isolating` flag?

**Comment by rosepark4861** [comment] 2023-02-21 23:52
https://regexper.com/ shows that the date pattern regex expression we are using has 5 matching groups (see the included regexper.com diagram for this date pattern).

![image](https://user-images.githubusercontent.com/60823338/220483729-6f32d3d9-5d2c-4cf5-9727-5c10f6d610d3.png)

It does not appear that the date pattern regex could be rewritten to have only one matching group.  We need to support two different date formats.  Even supporting only one date format would still require a regex pattern with multiple matching groups.

This route logic has been working properly for us for a long time while using the previous version of Flask.  It is only the new version of Flask which exhibits the incorrect parameter passing issue to the route handler function.

The regex pattern matching portion of the logic seems to work correctly with the new Flask version.  We have many routes registered and the proper route gets matched correctly and the proper route handling function is getting called each time.

The bug seems to be in the logic which passes the parameter values to the route handling function.  For some reason this logic is now passing incorrect parameter values to the route handling function with the new Flask version.

In our code base I have identified 5 separate routes so far where the new version of Flask is passing the parameters incorrectly to the route handling function.  In each of these 5 routes at least one of the parameters uses the regex date pattern to match the expected uri data for that parameter.  

As you suggested the date pattern regex we are using does seem to be a consistent factor which triggers the bug that causes incorrect parameters values to be passed to the route handling function.

**Comment by pgjones** [comment] 2023-02-22 18:02
Please see https://github.com/pallets/werkzeug/pull/2596 as a solution to this

**Comment by rosepark4861** [comment] 2023-02-22 21:34
The work around to change the nested groups from `(...)` to `(?:...)` worked like a charm.  Our code is fully functional again with the newer version of Flask.

A huge thank you to @pgjones for the quick response in investigating the issue, identifying the cause of the regression, identifying a work around for the problem, and coding a fix for the next release.  You're awesome!

**Closed** 2023-03-03 20:37 UTC
Labels: routing
