### ISSUE TITLE
Container, Iterable, MutableSet must be import from collections.abc

### ISSUE THREAD

**Issue by SaitoTsutomu** [pallets/werkzeug#1382] opened 2018-10-27 06:35 UTC
At line 16 of datastructures.py.

asis: `from collections import Container, Iterable, MutableSet`
tobe: `from collections.abc import Container, Iterable, MutableSet`
or
```
try:
    from collections.abc import Container, Iterable, MutableSet
except:
    from collections import Container, Iterable, MutableSet  # for 2.7
```

Because, `from collections import Container, Iterable, MutableSet` is deprecated and deleted at python 3.8.

**Comment by davidism** [comment] 2018-10-27 20:40
Duplicate of #1367

**Closed by davidism** 2018-10-27 20:40 UTC
