### ISSUE TITLE
web server written in  werkzeug  has memory leak under python 11.0

### ISSUE THREAD

**Issue by ochinchina** [pallets/werkzeug#2545] opened 2022-11-09 09:39 UTC
### Description

The memory of web server written in Werkzeug will keep increasing if it  is deployed to python 11.0 and tested with performance testing tool ab

### How to replicate the bug:

write a simple web server with following code and start it:

```python
from werkzeug.wrappers import Request, Response

@Request.application
def application(request):
    return Response("Hello, World!")

if __name__ == "__main__":
    from werkzeug.serving import run_simple
    run_simple("0.0.0.0", 5000, application)
```

test it with ab tool:

```shell
$ ab -n 10000 http://127.0.0.1:5000
```

after executing above command, almost the memory of the web server will increase every time and never decrease.

###  Expected behavior

the memory of above web server should not keep increasing.

### Environment:

- Python version: 11
- Werkzeug version: 2.2.2

**Comment by davidism** [comment] 2022-11-09 14:38
The web server is Python's `http.server`. Please report a bug there instead. Possibly a duplicate of https://github.com/python/cpython/issues/99205.

**Closed by davidism** 2022-11-09 14:38 UTC
