### ISSUE TITLE
werkzeug 0.15.2 and 0.15.3 fails with Python 3.8

### ISSUE THREAD

**Issue by xqt** [pallets/werkzeug#1558] opened 2019-05-26 12:06 UTC
`
  File "/home/travis/virtualenv/python3.8-dev/lib/python3.8/sitepackages/werkzeug/routing.py", line 1388, in add
    rule.bind(self)
  File "/home/travis/virtualenv/python3.8-dev/lib/python3.8/sitepackages/werkzeug/routing.py", line 730, in bind
    self.compile()
  File "/home/travis/virtualenv/python3.8-dev/lib/python3.8/sitepackages/werkzeug/routing.py", line 794, in compile
    self._build = self._compile_builder(False).__get__(self, None)
  File "/home/travis/virtualenv/python3.8-dev/lib/python3.8/sitepackages/werkzeug/routing.py", line 951, in _compile_builder
    code = compile(module, "<werkzeug routing>", "exec")
TypeError: required field "type_ignores" missing from Module
`
You'll find the complete traceback **[here](https://api.travis-ci.org/v3/job/537137615/log.txt|)**.

**Comment by davidism** [comment] 2019-05-26 12:34
Duplicate of https://github.com/pallets/werkzeug/issues/1551

**Closed by davidism** 2019-05-26 12:34 UTC
