### ISSUE TITLE
test_unix_socket hangs on MacOS due to OSError: AF_UNIX path too long

### ISSUE THREAD

**Issue by kbanc** [pallets/werkzeug#1871] opened 2020-06-29 17:40 UTC
When running `test_serving.py`, the tests hang on `test_unix_socket`. 

When debugging `test_unix_socket`, an OSError is thrown: 

```
Exception has occurred: OSError
AF_UNIX path too long
  File "/Users/katherinebancroft/dev/werkzeug/src/werkzeug/serving.py", line 596, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/Users/katherinebancroft/dev/werkzeug/src/werkzeug/serving.py", line 710, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/Users/katherinebancroft/dev/werkzeug/src/werkzeug/serving.py", line 852, in inner
    fd=fd,
  File "/Users/katherinebancroft/dev/werkzeug/src/werkzeug/serving.py", line 896, in run_simple
    inner()
  File "/Users/katherinebancroft/dev/werkzeug/tests/conftest.py", line 67, in _dev_server
    serving.run_simple(application=app, **testsuite_app.kwargs)
  File "/Users/katherinebancroft/dev/werkzeug/tests/conftest.py", line 186, in <module>
    _dev_server()
```

This seems to be because the default testing path is too long. Two similar issues: 
https://github.com/ethereum/trinity/issues/404
https://github.com/aio-libs/aiohttp/issues/3572

Path length limitations to be aware of.  
https://github.com/aio-libs/aiohttp/blob/385b03ef21415d062886e1caab74eb5b93fdb887/tests/conftest.py#L108
```
N.B. Different OS kernels have different fs path length limitations
for it. For Linux, it's 108, for HP-UX it's 92 (or higher) depending
on its version. For for most of the BSDs (Open, Free, macOS) it's
mostly 104 but sometimes it can be down to 100.
```

Environment:
- Python version: 3.7
- Werkzeug version: current master
- OSX: 10.15.5

**Comment by davidism** [comment] 2021-01-18 13:50
I'm not sure if something changed with a new pytest or just the fact that the test itself changed, but I can't reproduce this. I don't have a Mac, but tests have been passing consistently on CI. I checked the length of the path on Linux, and got the following:

```
Running pytest:
/tmp/pytest-of-david/pytest-3/test_server_unix_socket_0/test.sock
len: 65

Running tox (different tmp dir):
/home/david/Projects/werkzeug/.tox/py/tmp/test_server_unix_socket_0/test.sock
len: 77
```

Even substituting in a longer username or a different base path like your output doesn't get to the 92/100/104 character limits (the tox path gets to 85 characters). I'm going to close this for now as I don't want to pull in all the code to generate our own path if I don't have to, but I'll keep it in mind in case it comes up again.

**Comment by davidism** [comment] 2021-01-18 13:50
If you have time, give the latest code a try, I'd be interested if it's still failing and what the path is if so.

**Closed by davidism** 2021-01-18 13:50 UTC
