### ISSUE TITLE
werkzeug.server.shutdown

### ISSUE THREAD

**Issue by taivoe** [pallets/werkzeug#2387] opened 2022-04-12 20:59 UTC
Install self-signed cert into Django project to support HTTPS. Use mkcert.
Install Werkzeug.
`pip install werkzeug`
Start Django server.
`python3 manage.py runserver_plus --cert-file cert.pem --keyfile key-pem 0:8000`
Make request to root of app.

After first HTTPS request hits Django server:

```
Exception happened during processing of request from ('<local_ip>', 1205)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/<path_to_venv>/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 347, in handle
    super().handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/<path_to_venv>/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 243, in run_wsgi
    self.environ = environ = self.make_environ()
  File "/<path_to_venv>/venv/lib/python3.8/site-packages/django_extensions/management/commands/runserver_plus.py", line 326, in make_environ
    del environ['werkzeug.server.shutdown']
```

Environment:

- Python version: 3.8.10
- Werkzeug version: 2.1.1
- Django version: 4.0.3

Solution:

Change line 326 from:
`del environ['werkzeug.server.shutdown']
`
To:
`environ.pop('werkzeug.server.shutdown',None)`

**Comment by davidism** [comment] 2022-04-12 21:05
Duplicate of https://github.com/django-extensions/django-extensions/issues/1715

**Closed by davidism** 2022-04-12 21:05 UTC
