### ISSUE TITLE
werkzeug > 2.2.2 throws WinError 10038 during flask debug app reload

### ISSUE THREAD

**Issue by louking** [pallets/werkzeug#2837] opened 2024-01-18 20:24 UTC
This may be be a dup https://github.com/pallets/werkzeug/issues/2605 but that issue is locked.

I started with werkzeug 3.0.1, and during debug when my app reloads due to source change I see

```
 * Detected change in "c:\\Users\\lking\\Documents\\Lou's Software\\projects\\contracts\\contracts\\venv\\lib\\site-packages\\werkzeug\\http.py", reloading
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\threading.py", line 917, in run
  File "c:\Users\lking\Documents\Lou's Software\projects\contracts\contracts\venv\lib\site-packages\werkzeug\serving.py", line 806, in serve_forever    """
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\selectors.py", line 324, in select       
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\selectors.py", line 315, in _select      
    r, w, x = select.select(r, w, w, timeout)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
 * Restarting with stat
 ```

I downgraded to werkzeug==2.2.2 (based on suspicion in referenced issue that this was introduced in 2.2.3, plus that is what I had upgraded from), and the reload runs cleanly.

```
 * Detected change in "C:\\Users\\lking\\Documents\\Lou's Software\\projects\\contracts\\contracts\\contracts\\__init__.py", reloading
 * Restarting with stat
```

I'm running flask 2.3.3, so can't stay with werkzeug-2.2.2, but did the downgrade just for a test. Problem is indeed seen in werkzeug-2.3.7 which is minimum for flask 2.3.3 according to pip. 

Finally, problem is seen when running werkzeug 2.2.3, so I think this confirms the issue was introduced in that release.

Note: this doesn't seem to impact anything other than my reload -- the app runs fine otherwise as far as I have tested it.

I've tried `netsh winsock reset catalog` as recommended in https://stackoverflow.com/a/76444245/799921, but didn't yet try the other reset commands.

I should mention that when bringing up the app initially the error doesn't occur (I think that was what was tested in #2605), but does occur after source change / during reload.

Environment:

- Python version: 3.9.13
- Werkzeug version: 3.0.1

**Comment by davidism** [comment] 2024-01-18 20:57
Closing for the same reason the other was closed: I can't reproduce this issue with the information provided. Reloading on Windows works fine with the latest version. You're welcome to investigate and submit a patch, but otherwise this isn't a ticket that can be worked on.

**Closed by davidism** 2024-01-18 20:57 UTC

**Comment by louking** [comment] 2024-01-19 17:01
Sorry, but I was able to reproduce this with (sort of) minimal app with files in https://github.com/louking/helloflask/tree/2649998f1c1c2cf1f62e2674a2702798cf3039cd

I'm running windows 10 if that matters, python 3.9.13

I edit `__init__.py` (add whitespace) and save to cause the problem.

If I were to patch, it would be without much knowledge of the werkzeug internals. I would simply put 

```
    except OSError:
        pass
```
after the call to `super().serve_forever(poll_interval=poll_interval)` at https://github.com/pallets/werkzeug/blob/d3dd65a27388fbd39d146caacf2563639ba622f0/src/werkzeug/serving.py#L806

I suspect in 2.2.3 maybe a race condition with the cleanup of the socket was introduced during the restart. Maybe this only affects windows but I haven't found a line of code that is the culprit.

https://github.com/pallets/werkzeug/compare/2.2.2...2.2.3#diff-abeaeb33abe8954dc4551a4631392ac46ad65e8b9f8404cec0e276a0d345af3bR740 shows some possibilities in `serving.py` possibly 
 ee5f5cd4227a7fcf0508231ba9515e5c0d5874c8
