### ISSUE TITLE
Unable to get Content-Type header from parts in a multipart/form-data request

### ISSUE THREAD

**Issue by colin-nolan** [pallets/werkzeug#1848] opened 2020-06-16 19:56 UTC
Each part of a multipart/form-data request may contain a `Content-Type` header (https://tools.ietf.org/html/rfc7578#section-4.4). The multipart form parser doesn't currently make form field headers accessible, despite parsing them. We can see that the headers are available https://github.com/pallets/werkzeug/blob/master/src/werkzeug/formparser.py#L536 but are not returned https://github.com/pallets/werkzeug/blob/master/src/werkzeug/formparser.py#L563. The same is not true for files, which are lucky enough to get their data return in a specialised `FileStorage` object, opposed to a string (which makes maintaining backwards compatibility here problematic).

This issue was highlighted by @DmitriiTrofimov 2 years ago and he implemented `FormStorage`, that was complimentory to the `FileStorage`: https://github.com/pallets/werkzeug/pull/1290. However, this PR unfortunately didn't get merged.

Is there any appetite to add support for this functionality now?

**Comment by davidism** [comment] 2020-06-16 20:06
It wasn't merged because there doesn't appear to be a clean compatible way to implement it. Happy to review a PR if this is important to you.

**Comment by colin-nolan** [comment] 2020-06-16 21:06
Thanks @davidism. I've had a try at what I think should be a compatible way of providing hooks to get to this information in https://github.com/pallets/werkzeug/pull/1849.

**Comment by davidism** [comment] 2020-06-22 00:03
After looking at your implementation and the one by @DmitriiTrofminov, I think I've got a better idea of what I want.

I like that Dmitrii's implementation defined a `FormStorage` class, added support for it to the test client, and added tests. Even though I originally suggested it, it's probably not a great idea to subclass `str` for this though, it would be a very unexpected API. The implementation could have created a base `FieldStorage` class then made `FileStorage` a subclass to add the file-related methods, and possibly avoided duplication in a few other places too.

Your implementation shows that we could add some class attributes to make this customizable, but leaves the implementation up to the user. But there's really not a need for this, either you want the existing behavior, or you want the headers, there's not really any other way to parse the data.

Here's my idea. Create a `FieldStorage` base class, and have `MultiPartParser` always return it (or `FileStorage`). I think we can safely assume few enough projects are using `FormDataParser` directly that a breaking change in 2.0 is acceptable. Then `Request.form` by default only stores the values. Either we add a flag to control this, or just leave it up to the application to subclass.

@ThiefMaster thoughts on this?

**Comment by colin-nolan** [comment] 2020-08-02 16:34
Looping back around to this - @davidism I agree that the best solution involves an interface change, as you describe. I also agree that my implementation is essentially just a minimal (but non-disruptive) hack to support what is likely a niche use-case.

Would you be willing to merge #1849 - to make it at least possible for somone who wants the headers in v1 to get them - and for a cleaner but more disruptive change to go onto the backlog as the "correct' solution to this in a future version?

**Comment by davidism** [comment] 2020-10-20 01:34
After some more thought, I wasn't satisfied with the #1849 PR. It's fairly straightforward, but it means that if a user opts in to the extended information, `request.form` is no longer `key: value` and any existing code/extensions that rely on it won't work. I've gotten pretty far with implementing what I suggested above (with a new `request.form_headers` property to access it), but then I took another look at the [`multipart/form-data` spec](https://tools.ietf.org/html/rfc7578#section-4.2).

I think the problem is not that we don't expose headers for non-file fields, it's that the parser is assuming that the lack of a filename means the field is not a file, rather than the lack of a content type *or* filename. According to the spec:

> For form data that represents the content of a file, a name for the file SHOULD be supplied as well

> If the contents of a file are to be sent, the file data SHOULD be labeled with an appropriate media type, if known, or "application/octet-stream".

> The multipart/form-data media type does not support any MIME header fields in parts other than Content-Type, Content-Disposition, and (in limited circumstances) Content-Transfer-Encoding.  Other header fields MUST NOT be included and MUST be ignored.

We have two optional rules associated with files. Either the part has a filename, or the part has a content type. If it has neither, the only thing we can do is assume it's a plain value. If it has only a filename, we can use a default content type. If it has only a content type, we can use an empty filename.

Any other headers must be ignored. They are parsed only because they have to be to get to the data portion of the part, but they must not be used for plain parts, and only the content type header is relevant to files (which is why `FileStorage.content_type` and related properties are defined). I think the fact that `FileStorage` has arbitrary `headers` at all is just a convenience and should probably be removed to comply with the spec. Also, the parser does look at the `Content-Length` header even though it shouldn't and nothing is done with it in the default implementation.

The use case here and in #1290 seems to be that data that needs to be treated as a file with a content type was being uploaded without a filename, so the content type wasn't available because Werkzeug was treating it as a plain value. I think if I adjust the parser to treat "has filename or has content type" as files, that will solve the problem without going outside the intentions of the spec.

**Comment by davidism** [comment] 2020-10-20 02:24
#1290 does mention [OpenAPI](https://swagger.io/docs/specification/describing-request-body/multipart-requests/#headers) and the [Form-Data](https://github.com/form-data/form-data) library, which allows arbitrary headers, but that seems to be entirely against the HTTP `multipart/form-data` spec. I'm not particularly interested in enabling that sort of behavior. The objection was that if we don't proivde arbitrary headers, Werkzeug can't be used to write an OpenAPI server that uses this feature, but I think that's moot because you shouldn't be writing such an API according to the HTTP spec. If you want that regardless, you can use another multipart parser library and parse the form data yourself into whatever format you want, there's already enough hook methods in `Request` to accomplish that.

With #1788, we plan to greatly refactor the multipart parser. As part of that, there will probably be more ways to interface with the parser, such as getting the stream of `(name, value, headers)` (or something like that) instead of wrapped data.

**Comment by davidism** [comment] 2020-10-20 06:45
> I think if I adjust the parser to treat "has filename or has content type" as files, that will solve the problem

Then again, this isn't really true, the spec says a part can have a content type like `text/plain; charset=latin1` in order to specify the charset for a text value. If we changed the rule to "content type means file", this might unexpectedly put some parts in `files` instead of `form`. Any conforming client should be supplying a filename (JavaScript uses "file" or "blob" if it can't find a better name, for example) if the part is intended to be interpreted as a file.

My conclusion at this point is that according to the spec no other headers should be available, and the current rule of "has filename" is good enough for determining if a part is a file (with a content type) or a value (decoded with a charset).

**Closed** 2020-10-20 06:55 UTC

**Comment by pgjones** [comment] 2021-02-04 21:11
@colin-nolan you can access the headers using the [MultipartDecoder](https://github.com/pallets/werkzeug/blob/master/src/werkzeug/sansio/multipart.py) directly - hopefully that enables your usage.
