### ISSUE TITLE
Handling negative numbers in the IntegerConverter and FloatConverter

### ISSUE THREAD

**Issue by Skuldur** [pallets/werkzeug#1354] opened 2018-09-10 13:04 UTC
What is the reason for why the IntegerConverter and FloatConverter do not accept negative values?

I saw the discussion from 2012 where someone mentioned that this problem comes up quite often and my team just ran into the issue today. This allowed a bug to pass through our unit tests since our developer used -1 as an example of an ID that does not exist and would likely not exist.

Instead of actually executing the method it simply returned a 404 Status Code.

And if there is no major reason behind it, do you mind if I make a pull request adding negative number support to the number routing?

I saw some mention of signed=True parameter. Is that the method you would prefer for adding negative numbers to keep backwards compatibility?

Python: 3.6
Werkzeug:  0.14.1

If not, feel free to close this issue. :)

**Comment by davidism** [comment] 2018-09-10 13:07
Duplicate of #729

**Closed by davidism** 2018-09-10 13:07 UTC
