### ISSUE TITLE
Incorrect rule matched given two rules, one with a variable and suffix, another with two variables

### ISSUE THREAD

**Issue by abramclark** [pallets/werkzeug#727] opened 2015-04-23 07:58 UTC
There are two rules, the first one matching "/&lt;owner_name&gt;:Stuff" and the second matching "/&lt;owner_name&gt;:&lt;label_name&gt;". A request for "/fooman:Stuff" is matched by the second route, instead of the first as expected.

A workaround as suggested by ronny on #pocoo is to change the first route to match "/&lt;owner_name&gt;:&lt;any(Stuff):foo&gt;"

**Comment by skyline75489** [comment] 2015-10-18 02:08
Looks like a duplicate of #185

**Comment by davidism** [comment] 2017-06-05 12:56
Also reported at pallets/flask#1265.

**Closed** 2018-01-03 18:38 UTC
Labels: bug, routing, stupid behavior
