### ISSUE TITLE
Incorrect assumption in werkzeug.serving about socket behavior

### ISSUE THREAD

**Issue by d42** [pallets/werkzeug#920] opened 2016-05-01 18:56 UTC
As we all know socket.send() doesn't guarantee all of the data getting sent

and this line:
https://github.com/pallets/werkzeug/blob/03faf0569861e9d8c8c94785ad5560f735ba72da/werkzeug/serving.py#L165
combined with gevent and the greatest webscale technology, known as docker has led me to just that behavior with responses getting truncated :3

It seems like the socket.SocketIO  should care about it, but it doesn't

**Comment by untitaker** [comment] 2016-05-01 19:08
While you're probably correct (haven't done any research), please note that Werkzeug's server is only intended for development. Running it in Docker and with gevent leads me to believe that you don't use it for that purpose.

**Comment by d42** [comment] 2016-05-01 19:13
I've been actually using docker for development and part of the code used gevent monkeypatches quite frivulously.
I probably wouldn't even notice it if it wouldn't break dontpanic :3

**Comment by odony** [comment] 2017-10-25 17:02
I've experienced this bug in Python 3.5, but only when setting the underlying socket to non-blocking mode (e.g with `settimeout`). It turns out this is in fact caused by an upstream bug in Python 3: [issue24291](https://bugs.python.org/issue24291). The issue is fixed in Python 3.6 (see [issue26721](https://bugs.python.org/issue26721))

A workaround that has been implemented in other web servers is to wrap the `wfile` in an `io.BufferedWriter` (e.g in [CPython's wsgiref](https://github.com/python/cpython/commit/ed0425c60abe1b746b1ca5b4039984d2ad6583c4#diff-89b6670f2c31ce7e02eaf27cd2e7da99)) or to change the `wbufsize` to enable buffering by default (e.g. see [this gevent issue](https://github.com/gevent/gevent/issues/778#issuecomment-205048050))

Not sure if werkzeug wants to implements a workaround too, or considers it a non-werkzeug issue.

**Comment by RonnyPfannschmidt** [comment] 2017-10-25 19:01
based on the provided information i believe this indeed is either a gevent bug or a stdlib bug, werkzeug uses write + flush on a supposed buffered file,  which in turn should always work, now i wonder if this also happens on plain python, or only on gevent

**Comment by odony** [comment] 2017-10-26 11:33
@RonnyPfannschmidt yes, I get it without `gevent` too, I just need to use a non-blocking socket in combination with werkzeug's `WSGIRequestHandler`. Gevent was just another example of the many projects who are indirectly affected by the upstream bug in Python 3.5 :-)

**Comment by davidism** [comment] 2018-12-09 04:53
Given the circumstances this happens in, as well as the fact that it's fixed in Python 3.5 (3.4 goes EOL in March), I'm closing this.

**Closed by davidism** 2018-12-09 04:53 UTC
