### ISSUE TITLE
Non-empty CombinedMultiDict yields {} in dict(_) and json.dumps(_)

### ISSUE THREAD

**Issue by szym** [pallets/werkzeug#876] opened 2016-03-08 08:32 UTC
``` python
a = MultiDict([('a', 'b'), ('a', 'c')])
b = CombinedMultiDict([a])
print(dict(b))
> {}
# Expected same as print(dict(a)) == {'a': ['b', 'c']}
print(json.dumps(b))
# Expected same as json.dumps(a) == '{"a": "b"}'
> '{}'
```

Happens in python 2.7 and 3.4 with werkzeug 0.11.4

**Comment by mitsuhiko** [comment] 2016-04-16 11:30
We can't do anything about `dict()`. That's a python "bug".

**Comment by untitaker** [comment] 2016-04-16 16:48
If we stop subclassing `dict` this might be doable. Using `collections.Mapping` seems like a viable alternative.

**Comment by davidism** [comment] 2018-11-26 16:51
`dict(b)` works, I get `{"a": "b"}` (which is not what you expected, but all the multidicts return their first item only). `b.as_dict(flat=False)` will get you what you were expecting.

----

`json.dumps` is harder to solve. The issue is that `CombinedMultiDict` isn't really a dict, it's only a view on other dicts, and so no data is stored. `dumps` is implemented in C, and does [something like `dict.items(b)` to get the items.](https://github.com/python/cpython/blob/5719f275b7153a00a800f5481271a6fc26659c65/Modules/_json.c#L1607) This is an issue with the C implementation, the Python implementation calls `b.items()` and returns the expected output.

Switching to `Mapping` seems like a lot of work:

* All subclasses inherit from `dict` through `TypeConversionDict`, so that would need to be extracted to a mixin.
* Most subclasses should still inherit from `dict`, otherwise existing behavior (including working `json.dumps`) breaks.
* But if `MultiDict` still inherits from `dict`, we have the same problem that `CombinedMultiDict` would be a subclass of it as well. So we'd have to extract `MultiDict` into a mixin too.
* If we got to the point where `CombinedMultiDict` didn't inherit from `dict` anymore, that would now mean that `json.dumps` would raise an error about not recognizing it, so users would have to implement `default()` to handle it.

**Comment by davidism** [comment] 2018-11-26 17:01
Given that users would have to manually intervene with `default` anyway, it seems much more straightforward that if they're in a situation where they want to serialize a `CombinedMultiDict`, they should pre-process their data by calling `b.as_dict()` before passing to `json.dumps`.

I can report this to CPython, since they should probably look up and call `items` for dict subclasses. It looks like there might be some work related to object overrids in general: https://bugs.python.org/issue12657#msg329960

**Comment by davidism** [comment] 2018-12-10 14:58
Closing this as I don't think any of the solutions besides "pre-process before serializing" are viable at this time.

**Closed by davidism** 2018-12-10 14:58 UTC
Labels: bug
