### ISSUE TITLE
"Cookie header" munge bad and good cookies together

### ISSUE THREAD

**Issue by dorfsmay** [pallets/werkzeug#1117] opened 2017-05-14 00:41 UTC
werkzeug munges bad and good cookies together, for example this code:

```python2
#!/usr/bin/env python2

import sys
sys.path.insert(0, '/export/scratch/repos/forks/werkzeug')
from werkzeug.wrappers import Request, Response

@Request.application
def application(request):
    print(request.cookies)
    return Response('Hello World!\n')

if __name__ == '__main__':
    from werkzeug.serving import run_simple
    run_simple('localhost', 8080, application)
```

Will result in:
`curl -b 'SID=31d4d96e407aad42; muffin ; lang=en-US;' localhost:8080`

==> `{'SID': '31d4d96e407aad42', 'muffin ; lang': 'en-US'}`

**Comment by davidism** [comment] 2017-05-14 02:09
Duplicate of #841

**Closed by davidism** 2017-05-14 02:09 UTC
