### ISSUE TITLE
OSError: [WinError 10038] An operation was attempted on something that is not a socket

### ISSUE THREAD

**Issue by Vishwamithra37** [pallets/werkzeug#2853] opened 2024-02-21 11:50 UTC
Intsall latest version of flask in debug mode in a windows environment.
Try to make a change in the app.py / main.py and you will see this:

 * Detected change in 'E:\\2Semmasters\\slots_own\\slots2\\Resources_API\\routes.py', reloading
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "H:\py39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "H:\py39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "E:\2Semmasters\slots_own\slots2\apples\lib\site-packages\werkzeug\serving.py", line 806, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
  File "H:\py39\lib\socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "H:\py39\lib\selectors.py", line 324, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "H:\py39\lib\selectors.py", line 315, in _select
    r, w, x = select.select(r, w, w, timeout)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
```

Expected:
This should not happen and it should easily hot reload without any error from the OS side.

Environment:

- Python version: 3.9
- Werkzeug version:  3.0.1

**Comment by Vishwamithra37** [comment] 2024-02-21 11:56
The same issue does not happen when I revert back the werkzeug to version 2.2.2 . And probably any version which has this:
```
    if sys.platform == 'win32':
        def _select(self, r, w, _, timeout=None):
            r, w, x = select.select(r, w, w, timeout)
            return r, w + x, []
    else:
        _select = select.select
```
lib\selectors.py
In the said file.

**Comment by davidism** [comment] 2024-02-21 15:17
Duplicate of https://github.com/pallets/werkzeug/issues/2605. I continue to be unable to reproduce the issue. Be sure to provide a minimal reproducible example when reporting an issue. Currently, no one has supplied one that actually reproduces the issue for me, so I can't work on it.

**Closed by davidism** 2024-02-21 15:17 UTC
