### ISSUE TITLE
Reloader does mysterious things with the shebang line in your script, reports errors with it confusingly

### ISSUE THREAD

**Issue by fake-name** [pallets/werkzeug#1557] opened 2019-05-24 06:35 UTC
I have a project that I can run in either debug or release mode. I'm [launching the debug server manually via python](https://github.com/fake-name/ReadableWebProxy/blob/master/run.py#L56-L58) (I really dislike custom launcher scripts, because I generally want to start additional background threads for other processes. Just let me use a python call!).

Right now, with the latest flask/werkzeug, the app works properly in release mode (which uses cherrypy as the server. However, if I launch it in debug mode `app.run(host='0.0.0.0', port=5001, debug=True)`, it fails to load:

```
durr@nrwpscrape /m/S/ReadableWebProxy> python3 run.py  debug
Setting up loggers....
Main.Test.MainThread PID: 13917  - INFO - Logging Active
done
Flask running in debug mode!
Setting redis config
redis configured
Need to load rules (True, True)
Loaded rulesets (54):
Need to load special-url handling ruleset (False, True)
Loaded rulesets (54):
Need to load special-url handling ruleset (True, True)
Main.ChromeController.WrapperGenerator.MainThread PID: 13917  - INFO - ChromeController wrapper is up to date. Nothing to do
Processing plugins: 26, active filters: 10
Main.DB-Engine.MainThread PID: 13917  - INFO - INFO: Creating engine for process! Engine name: 'MainProcess-MainThread'
Main.DbCookieJar.MainThread PID: 13917  - INFO - Loaded 2 cookies from db.
Main.DbCookieJar.MainThread PID: 13917  - INFO - Loaded 2 cookies from db.
Main.DbCookieJar.MainThread PID: 13917  - INFO - Loaded 0 cookies from db.
Main.DbCookieJar.MainThread PID: 13917  - INFO - Loaded 0 cookies from db.
Running in debug mode.
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
werkzeug.MainThread PID: 13917  - INFO -  * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
werkzeug.MainThread PID: 13917  - INFO -  * Restarting with stat
Main.MainThread PID: 13917  - CRITICAL - Uncaught exception!
Main.MainThread PID: 13917  - CRITICAL - Uncaught exception
Traceback (most recent call last):
  File "run.py", line 120, in <module>
    go()
  File "run.py", line 58, in go
    app.run(host='0.0.0.0', port=5001, debug=True)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 988, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
    sys.exit(reloader.restart_with_reloader())
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
    exit_code = subprocess.call(args, env=new_environ, close_fds=False)
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/media/Scripts/ReadableWebProxy/run.py': '/media/Scripts/ReadableWebProxy/run.py'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/media/Scripts/ReadableWebProxy/common/util/DbCookieJar.py", line 180, in save
    with self.db.session_context("cookiejar") as sess:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/media/Scripts/ReadableWebProxy/common/db_engine.py", line 143, in session_context
    sess = get_db_session(postfix=name + 'context-sess')
  File "/media/Scripts/ReadableWebProxy/common/db_engine.py", line 71, in get_db_session
    return g.session
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/local.py", line 307, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python3.6/dist-packages/flask/globals.py", line 44, in _lookup_app_object
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in some way. To solve
this, set up an application context with app.app_context().  See the
documentation for more information.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/media/Scripts/ReadableWebProxy/common/util/DbCookieJar.py", line 180, in save
    with self.db.session_context("cookiejar") as sess:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/media/Scripts/ReadableWebProxy/common/db_engine.py", line 143, in session_context
    sess = get_db_session(postfix=name + 'context-sess')
  File "/media/Scripts/ReadableWebProxy/common/db_engine.py", line 71, in get_db_session
    return g.session
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/local.py", line 307, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python3.6/dist-packages/flask/globals.py", line 44, in _lookup_app_object
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
to interface with the current application object in some way. To solve
this, set up an application context with app.app_context().  See the
documentation for more information.
durr@nrwpscrape /m/S/ReadableWebProxy>
```

Now, after a bunch of experimenting, it turns out that **if the shebang line is wrong, the reloader fails**. 

I have no idea why the shebang line is even involved. I'm invoking the script as `python3 <scriptname>`. Additionally, the debug output is actively unhelpful. I spent quite a while looking for mount issues with the NFS mount the python files I'm trying to run before figuring out that the path reported as not found was actually wrong.

Alternatively, if I mark the script as *not* executable, the reloader still fails, which makes me think something outside of the shell is trying to parse the script shebang line? Removing the shebang line also fails, with the same error.

This *used* to work at some point 6-12 months ago, but I haven't done work on the webdev end of this project in about that period of time (so I haven't need debug mode).

Anyways, just outputting that the interpreter loaded from the shebang line is invalid would help a lot, though just not reporting a incorrect FileNotFound would be plenty helpful.

------

```

durr@nrwpscrape:/media/Scripts/ReadableWebProxy$ uname -a
Linux nrwpscrape 4.15.18-13-pve #1 SMP PVE 4.15.18-37 (Sat, 13 Apr 2019 21:09:15 +0200) x86_64 x86_64 x86_64 GNU/Linux
durr@nrwpscrape:/media/Scripts/ReadableWebProxy$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"


Python 3.6.7
Werkzeug==0.15.4
Flask==1.0.3
```

**Comment by davidism** [comment] 2019-05-24 13:23
Duplicate of #1482

**Closed by davidism** 2019-05-24 13:23 UTC

**Comment by davidism** [comment] 2019-05-24 13:31
If you mark a script executable, it should have an interpreter line. Based on your description, I created a basic test by defining an app module and a run module, with the run module printing `sys.argv` and calling `app.run(debug=True)`, and it worked as expected.

I cannot reproduce the issues you're seeing when removing the executable bit. Most of the text and code given in the issue don't seem relevant to the executable issue you're asking about, they seem like other issues with your code

**Comment by fake-name** [comment] 2019-05-24 21:56
The executable bit is orthogonal to the issue.

The problem here is that something depends on a valid shebang line being present independent of whether the script is marked as executable.

 - Valid shebang line, executable script -> reloader works
 - Valid shebang line, **not** executable script -> reloader works
 - Incorrect shebang line, executable script -> reloader fails and points to a missing file that is present.
 - Incorrect shebang line, **not** executable script  -> reloader fails and points to a missing file that is present.
 - No shebang line, executable script -> reloader fails and points to a missing file that is present.
 - No shebang line, **not** executable script  -> reloader fails and points to a missing file that is present.

I mentioned the executable thing because it seems that the shebang line is read **even when the script isn't marked executable**. 

In all failure cases, the error output points to the `<filename>` of the python file being invoked as `python3 <filename>` being missing, when this is not true. The problem is that the python executable is wrong (and therefore missing). 

Whatever mechanism in the reloader that checks for proper start reports the script file being missing in all cases, even when the issue is a wrong interpreter, rather then a missing script file.

**Comment by davidism** [comment] 2019-05-24 22:04
I'm sorry, I can't reproduce the cases you're describing.

**Comment by fake-name** [comment] 2019-05-24 22:14
Take the following file:

```

from flask import Flask

app = Flask(__name__)


@app.route('/')
def hello_world():
	return 'Hello, world!'

if __name__ == '__main__':
	app.run(debug=True, host='0.0.0.0')
```

Put it in a file named `wat.py`. Invoke: `python3 wat.py`. It explodes.

**Comment by davidism** [comment] 2019-05-24 22:18
It works fine for me.

**Comment by fake-name** [comment] 2019-05-24 22:22
Well what the heck.

**Comment by fake-name** [comment] 2019-05-24 22:34
Ok, this is really dumb. I went into the `_reloader.py` and added a debug print, and the issue went away.

I think a out-of-date .pyc file somewhere was breaking things.
