### ISSUE TITLE
Reloader can't find script when path contains dot on Windows

### ISSUE THREAD

**Issue by greyli** [pallets/werkzeug#1619] opened 2019-07-24 08:54 UTC
On Windows with Werkzeug 0.15.5, when in dev mode (`FLASK_ENV=development`), if the virtual environment path contains a dot, for example:
- D:\\repos\\flask-examples\\.venv\\Scripts\\flask
- C:\\Users\\greyli\\.virtualenvs\\flask-examples-qatl1Peb\\Scripts\\flask

Now `flask run` will throw an error:
```bash
> flask run
d:\repos\flask-examples\.venv\scripts\python.exe: Error while finding module specification for 
'D:\\repos\\flask-examples\\.venv\\Scripts\\flask' (ModuleNotFoundError: No module named 'D:\\repos\\flask-examples\\')
```
Notice the output, it seems that it cut the module path with the dot. If I change the virtual environment folder to `venv` (remove the dot in folder name), everything will be ok. The `.exe` is also missing on the output above, but I can't reproduce issue in #1614, it's weried...

Besides, these methods will prevent this error:

- use `python -m flask run`
- downgrade Werkzeug to 0.15.4

IMO, this issue related with #1614, and may caused by the dot handling in https://github.com/pallets/werkzeug/commit/e686ae714a6ba436912a2ce7ea2da615a8d5d0bf.

### Environment
- Win10
- Python 3.6 / 3.7
- Flask 1.1.1
- Werkzeug 0.15.5

**Comment by sorgloomer** [comment] 2019-08-09 14:07
Are you sure this is an issue with dots? My path doesn't have a dot in it and I still see a similar error:

```
C:\workspace\aliz\temp\flaskbug>set FLASK_DEBUG=1 && flask run
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
c:\programs\python37\python.exe: No module named C:\programs\Python37\Scripts\flask
```

**Comment by greyli** [comment] 2019-08-11 09:13
@sorgloomer Hi, your issue was releated to #1614.

**Comment by frostming** [comment] 2019-08-20 03:15
@greyli I can't reproduce the issue with dots, can you verify it against #1627 ?

**Comment by davidism** [comment] 2019-08-31 19:07
Seems to be the same issue as #1627, or at least fixed by it. I think this was just a different error message due to Python version differences.

**Closed by davidism** 2019-08-31 19:07 UTC
