### ISSUE TITLE
debugger ui: display same context information as django (debug) error page

### ISSUE THREAD

**Issue by valentijnscholten** [pallets/werkzeug#2018] opened 2021-01-24 20:13 UTC
Request:
Add the extra context information to the debugging page below the traceback. Similar to what django itself does.

Considered:
Most or maybe even all of this info can probably be obtained by using the console, but it would be a lot more practical if it was already there. 

I am new to the Werkzeug debugger and I like the console. I know I can get the local variables by using the console, but:
- it would be a lot more convenient if they were there by default;
- printing / dumping them in console takes effort to make them readable;

Examples:
![image](https://user-images.githubusercontent.com/4426050/105642219-b464cc00-5e88-11eb-9e48-c9d91c2377d5.png)
![image](https://user-images.githubusercontent.com/4426050/105642240-e5450100-5e88-11eb-80d8-db757440c30c.png)
![image](https://user-images.githubusercontent.com/4426050/105642254-f3931d00-5e88-11eb-8045-e5f8cab1c53b.png)

**Comment by davidism** [comment] 2021-01-24 20:17
Duplicate of #1309

**Comment by davidism** [comment] 2021-01-24 20:17
Duplicate of #1309

**Closed by davidism** 2021-01-24 20:17 UTC

**Comment by valentijnscholten** [comment] 2021-01-24 20:20
@davidism I think #1309 is about local variables _inside_  the traceback view. My request here is about the values printed by django  _below_ the traceback view and are something separate from local variables.
![image](https://user-images.githubusercontent.com/4426050/105642423-e296db80-5e89-11eb-869f-dd3379710004.png)

or do you see it differently?
