### ISSUE TITLE
Environment Building doc is Python2 only

### ISSUE THREAD

**Issue by lafrech** [pallets/werkzeug#1637] opened 2019-09-06 19:14 UTC
Trying to work with `EnvironBuilder`, I realized the doc example is Python 2 only.

https://werkzeug.palletsprojects.com/en/0.15.x/test/#environment-building

For people not familiar with Python 2 vs. 3 differences about bytes/str it can be confusing. 

Besides, since Python 2 reaches end of life, it would make sense to have all the doc examples expressed as Python 3.

--------------------------------------------------------------------------------------------

Here's the Python 2 doc example:

```py
from werkzeug.test import EnvironBuilder
from StringIO import StringIO
builder = EnvironBuilder(method='POST', data={'foo': 'this is some text', 'file': (StringIO('my file contents'), 'test.txt')})
env = builder.get_environ()

from werkzeug.wrappers import Request
req = Request(env)
req.form['foo']
# u'this is some text'
req.files['file']
# <FileStorage: u'test.txt' ('text/plain')>
req.files['file'].read()
# 'my file contents'
```

Trying to translate this to Python 3:

Let's fix the import

```py
from io import StringIO
```

```py
env = builder.get_environ()
TypeError: a bytes-like object is required, not 'str'
```

OK, so we need bytes.

```py
from io import BytesIO
builder = EnvironBuilder(method='POST', data={'foo': 'this is some text', 'file': (BytesIO('my file contents'.encode()), 'test.txt')})
```

If this is the right way to proceed, then the docs could read

```py
from werkzeug.test import EnvironBuilder
from io import BytesIO
builder = EnvironBuilder(method='POST', data={'foo': 'this is some text', 'file': (BytesIO('my file contents'.encode()), 'test.txt')})
env = builder.get_environ()

from werkzeug.wrappers import Request
req = Request(env)
req.form['foo']
# 'this is some text'
req.files['file']
# <FileStorage: u'test.txt' ('text/plain')>
req.files['file'].read()
# b'my file contents'
```

I don't mind sending a PR but I'm not 100% confident this is the right change.

**Comment by davidism** [comment] 2019-09-06 19:18
Duplicate of pallets/meta#26. PRs welcome, but I'm not going to leave this open since the whole docs need to be updated at some point.

**Closed by davidism** 2019-09-06 19:18 UTC
