### ISSUE TITLE
Werkzeug starting a subprocess out of pycharm fails on windows due to whitespaces in path (only py>=3.10)

### ISSUE THREAD

**Issue by vogt31337** [pallets/werkzeug#2756] opened 2023-08-01 14:00 UTC
Outline
--
Trying to debug a Flask application on python 3.11 out of pycharm exits with an exit code 2 and a message showing only half of a path.

Replication
--
Well just create an example application with flask on python env with py >= 3.10 and it will fail immediately. After displaying debug mode: on

Environment:
--
- Python version: 3.11
- Werkzeug version: 2.2.3
- Windows 10 22AH2

Possible fix?
--
I've narrowed down the bug to:
```
_reloader.py, line 269:
        while True:
            _log("info", f" * Restarting with {self.name}")
            args = _get_args_for_reloading()
            new_environ = os.environ.copy()
            new_environ["WERKZEUG_RUN_MAIN"] = "true"
            exit_code = subprocess.call(args, env=new_environ, close_fds=False)
```
args contains a list of arguments to execute. On windows pycharm hands over a pydev tool for debugging (e.g.: "C:\Program Files\JetBrains\PyCharm 2023.1.4\plugins\python\helpers\pydev") which contains whitespaces. For some reason subprocess.call needs this string to contain double double quotes in front and at the back or otherwise it will only try to execute until the first whitespace. Which results in the error (can't find "C:\Program "). This seems to be a particular problem with windows and the standard shell.

A possible fix would be:
```
_reloader.py, line 171:
    if sys.version_info >= (3, 10):
        # sys.orig_argv, added in Python 3.10, contains the exact args used to invoke
        # Python. Still replace argv[0] with sys.executable for accuracy.
        return [sys.executable, '""' + sys.orig_argv[1] + '""', *sys.orig_argv[2:]]
```

which would produce the encapsulation. Since this "fix" seems pretty janky to me and since I don't understand anything about Werkzeug, I won't make a PR, probably you guys understand what's happening here. And I think in older python versions this is not a problem because some magic is happening below line 171...

**Comment by ThiefMaster** [comment] 2023-08-01 14:02
Don't use the reloader if you want to use an external debugger.

**Comment by vogt31337** [comment] 2023-08-01 14:34
@ThiefMaster sorry but I can't influence that part. Pycharm is doing this on "its own" when you press debug. Maybe if you could provide more information I can write them a bug report so that they'll change their tooling.

As for the second part, yup I've read that too, but just seems to be wrong. Since it's only working with the double double quotes. Which is pretty annoying since it hinders every debugging effort...

**Comment by ThiefMaster** [comment] 2023-08-01 14:36
I'm not asking you to change tooling, I'm just suggesting you to disable the reloader; this is done by passing `--no-reload` (possibly `--no-debugger` as well so exceptions actually bubble up to the pycharm debugger) to the `flask run` call.

**Comment by davidism** [comment] 2023-08-01 14:36
Duplicate of https://github.com/pallets/werkzeug/issues/2707, this is an issue with PyCharm and has been reported here: https://youtrack.jetbrains.com/issue/PY-60819/FLASKDEBUG1-breaks-debugger-when-Python-PyCharm-installation-path-has-spaces, click the thumbs up icon next to the title to vote for it to be fixed.

**Closed by davidism** 2023-08-01 14:36 UTC

**Comment by davidism** [comment] 2023-08-01 14:42
Please don't go over to the other issue and suggest that the issue is with Werkzeug after we tell you it's not.
