### ISSUE TITLE
parse_rule import bug

### ISSUE THREAD

**Issue by Nemulo** [pallets/werkzeug#2486] opened 2022-08-02 13:56 UTC
from flask_restx import Api
 File "/usr/local/lib/python3.9/site-packages/flask_restx/__init__.py", line 5, in <module>
from .api import Api  # noqa
File "/usr/local/lib/python3.9/site-packages/flask_restx/api.py", line 50, in <module>
from .swagger import Swagger
File "/usr/local/lib/python3.9/site-packages/flask_restx/swagger.py", line 18, in <module>
from werkzeug.routing import parse_rule
ImportError: cannot import name 'parse_rule' from 'werkzeug.routing' (/usr/local/lib/python3.9/site-packages/werkzeug/routing/__init__.py)

happens in every service on starting when i want to use Api from flask_restx

Environment:

- Python version:3.10.1
- Werkzeug version:2.2.1

**Comment by davidism** [comment] 2022-08-02 13:57
Duplicate of https://github.com/pallets/werkzeug/issues/2466

**Closed by davidism** 2022-08-02 13:57 UTC
