### ISSUE TITLE
Replace sys.args containing whitespaces.

### ISSUE THREAD

**Issue by skyzip2142** [pallets/werkzeug#2782] opened 2023-09-11 12:57 UTC
First of all, I did not really know if this should be a feature request or a bug report, as I could not really find reasonable workarounds for my issue.

Sadly, on specific platforms (eg. win32) whitespaces in _filepaths_ are common.
In the file  [_reloader.py](https://github.com/pallets/werkzeug/blob/main/src/werkzeug/_reloader.py) the command line arguments are passed as is, regardless the fact that `subprocess.call` cannot process arguments with whitespaces correctly.
This would be solved relatively easily with the following modification (`_get_args_for_reloading`):

The suggested code changes could be seen in the dropdown.

<details>

<summary>Handling arguments with whitespaces.</summary>

```py
def _get_args_for_reloading() -> list[str]:
    """Determine how the script was executed, and return the args needed
    to execute it again in a new process.
    """
    spacer = re.compile(r'\s')

    if sys.version_info >= (3, 10):
        # sys.orig_argv, added in Python 3.10, contains the exact args used to invoke
        # Python. Still replace argv[0] with sys.executable for accuracy.
        orig_argv = sys.orig_argv
        executable = sys.executable
        if sys.platform == 'win32':
            orig_argv = [
                arg if spacer.search(arg) is None else f'""{arg}""'
                for arg in orig_argv
            ]
            if spacer.search(executable) is not None:
                executable = f'""{executable}""'
        return [executable, *orig_argv[1:]]

    rv = [sys.executable]
    py_script = sys.argv[0]
    args = sys.argv[1:]
    # Need to look at main module to determine how it was executed.
    __main__ = sys.modules["__main__"]

    # The value of __package__ indicates how Python was called. It may
    # not exist if a setuptools script is installed as an egg. It may be
    # set incorrectly for entry points created with pip on Windows.
    if getattr(__main__, "__package__", None) is None or (
        os.name == "nt"
        and __main__.__package__ == ""
        and not os.path.exists(py_script)
        and os.path.exists(f"{py_script}.exe")
    ):
        # Executed a file, like "python app.py".
        py_script = os.path.abspath(py_script)

        if os.name == "nt":
            # Windows entry points have ".exe" extension and should be
            # called directly.
            if not os.path.exists(py_script) and os.path.exists(f"{py_script}.exe"):
                py_script += ".exe"

            if (
                os.path.splitext(sys.executable)[1] == ".exe"
                and os.path.splitext(py_script)[1] == ".exe"
            ):
                rv.pop(0)

        rv.append(py_script)
    else:
        # Executed a module, like "python -m werkzeug.serving".
        if os.path.isfile(py_script):
            # Rewritten by Python from "-m script" to "/path/to/script.py".
            py_module = t.cast(str, __main__.__package__)
            name = os.path.splitext(os.path.basename(py_script))[0]

            if name != "__main__":
                py_module += f".{name}"
        else:
            # Incorrectly rewritten by pydevd debugger from "-m script" to "script".
            py_module = py_script

        rv.extend(("-m", py_module.lstrip(".")))

    rv.extend(args)

    if sys.platform == 'win32':
        rv = [
            arg if spacer.search(arg) is None else f'""{arg}""'
            for arg in rv
        ]

    return rv
```
</details>

At the moment applications depending on this package (like Flask), do not handle this issue, and failing to start up the development server, as they are using werkzeug for this. This should be able to solve this issue on win32 platforms, regardless of where python was installed.

**Comment by davidism** [comment] 2023-09-11 14:04
Duplicate of https://github.com/pallets/werkzeug/issues/2702
Duplicate of https://github.com/pallets/werkzeug/issues/2707
Duplicate of https://github.com/pallets/werkzeug/issues/2756

I can't reproduce this issue as reported. Spaces in arguments to `subprocess.run` work fine on Windows. PyCharm on Windows does have a bug that is actively being worked on: https://youtrack.jetbrains.com/issue/PY-60819/FLASKDEBUG1-breaks-debugger-when-Python-PyCharm-installation-path-has-spaces

**Closed by davidism** 2023-09-11 14:04 UTC
