### ISSUE TITLE
bad arg-parse in python versions >= (3, 10)

### ISSUE THREAD

**Issue by killershotpy** [pallets/werkzeug#2879] opened 2024-04-12 07:19 UTC
After installing the new version of Pycharm CE 2024.1, encountered a problem that was described here: https://youtrack.jetbrains.com/issue/PY-60819/FLASKDEBUG1-breaks-debugger-when-Python-PyCharm-installation-path-has-spaces
After that I immediately went to the debugger to see the full path of the error trace.

The error was solved by changing the **debug=True** -> **False** flag.
The initial entry point looked like this:
<img width="344" alt="image" src="https://github.com/pallets/werkzeug/assets/77852725/77f42ca8-1d4c-4e37-976a-45cfd905fb0a">

After that, I checked the trace, and found out that after the python version is determined, the "_get_args_for_reloading()" function does not work correctly.

For comparison, see "args" with python 3.9.10 (1pic) and after "args" with python 3.12.3 (2 pic):
<img width="631" alt="image" src="https://github.com/pallets/werkzeug/assets/77852725/76a076fb-7347-42eb-994e-bfe3479c1a7a">

(1 picture, 3.9.10 python)

<img width="927" alt="image" src="https://github.com/pallets/werkzeug/assets/77852725/9318c20b-c93a-4384-9db2-d12531d34c76">
(2 picture, 3.12.3 python)

As you can see in the screenshots, arg-parser does not work correctly when branching the logic when determining the version:

    def _get_args_for_reloading() -> list[str]:  # (167 line)
        if sys.version_info >= (3, 10):  # (171 line)
            # sys.orig_argv, added in Python 3.10, contains the exact args used to invoke
            # Python. Still replace argv[0] with sys.executable for accuracy.
            return [sys.executable, *sys.orig_argv[1:]]

in file "...werkzeug\\_reloader.py"
as a result, subprocess.call() is called with invalid arguments.

I also traced subprocess.call() itself, up to Popen(), and these are the arguments passed to the _winapi call:
<img width="1000" alt="image" src="https://github.com/pallets/werkzeug/assets/77852725/62a5ea02-34dc-4a93-872f-23ec64ed252a">
As you can see, the arguments passed are incorrect.

I also tested running cmd.exe in the console directly test_local.py entry point, with the same parameters where debug flag=True and python interpreter 3.12.3
The error does not reproduce, apparently because Pycharm passes too many arguments when running in debugger...
<img width="788" alt="image" src="https://github.com/pallets/werkzeug/assets/77852725/65664649-59e4-4702-8d21-bd49ba987076">

As I found out later, after testing:
debug=True
python version 3.12.3
if these lines are commented out:

    def _get_args_for_reloading() -> list[str]:  # (167 line)
        # if sys.version_info >= (3, 10):  # (171 line)
            # sys.orig_argv, added in Python 3.10, contains the exact args used to invoke
            # Python. Still replace argv[0] with sys.executable for accuracy.
            # return [sys.executable, *sys.orig_argv[1:]]

The debugger works without problems, arguments are passed correctly, Pycharm does not stop compilation of the code, and automatic reloading (restarting the application) works correctly after any change in the project dirrectories.

Obviously, there are only 2 solutions:
1. fix arg-parser after branching the version checking logic of the python interpreter.
2. change subprocess.call() to any other calling option, such as os.command() for windows (and only for that OS)

Of course, I have too little experience in writing python code to take advice, but it is obvious that the problem here is the misinterpretation of arg variables, which are subsequently passed to the subprocess.call() function.

Environment:
- Python version: 3.9.10 & 3.12.3
- Werkzeug version: 3.0.2

**Comment by davidism** [comment] 2024-04-12 17:14
Duplicate of https://github.com/pallets/werkzeug/issues/2702
Duplicate of https://github.com/pallets/werkzeug/issues/2707
Duplicate of https://github.com/pallets/werkzeug/issues/2756
Duplicate of https://github.com/pallets/werkzeug/issues/2782

Spaces in arguments to `subprocess.run` work fine on Windows, this isn't a bug in Werkzeug, Flask, or `subprocess.run`. As described in the linked PyCharm issue and its duplicates, the bug is in PyCharm on Windows and it appears they're actively working on it.

**Closed by davidism** 2024-04-12 17:14 UTC

**Comment by killershotpy** [comment] 2024-04-12 22:09
I apologize for not paying attention, thanks for the reply...

Your product is the best!
